=== Ajay-Chandrasekaran/rest-automation/src/test/resources/jsonschemas/customerenergyplanactivated-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "message": {
      "type": "string"
    },
    "success": {
      "type": "boolean"
    },
    "status": {
      "type": "integer"
    },
    "response": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "lastUpdatedDate": {
              "type": "string"
            },
            "lastUpdatedBy": {
              "type": "string"
            },
            "createdDate": {
              "type": "string"
            },
            "createdBy": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "customerId": {
              "type": "string"
            },
            "energyPlanInfo": {
              "type": "object",
              "properties": {
                "lastUpdatedDate": {
                  "type": "string"
                },
                "lastUpdatedBy": {
                  "type": "string"
                },
                "createdDate": {
                  "type": "string"
                },
                "createdBy": {
                  "type": "string"
                },
                "id": {
                  "type": "integer"
                },
                "offer": {
                  "type": "object",
                  "properties": {
                    "lastUpdatedDate": {
                      "type": "string"
                    },
                    "lastUpdatedBy": {
                      "type": "string"
                    },
                    "createdDate": {
                      "type": "string"
                    },
                    "createdBy": {
                      "type": "string"
                    },
                    "offerCode": {
                      "type": "string"
                    },
                    "offerName": {
                      "type": "string"
                    },
                    "countryCode": {
                      "type": "string"
                    },
                    "countryName": {
                      "type": "string"
                    },
                    "offerImagePath": {
                      "type": "string"
                    },
                    "status": {
                      "type": "integer"
                    },
                    "description": {
                      "type": "string"
                    },
                    "startDate": {
                      "type": "string"
                    },
                    "endDate": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "lastUpdatedDate",
                    "lastUpdatedBy",
                    "createdDate",
                    "createdBy",
                    "offerCode",
                    "offerName",
                    "countryCode",
                    "countryName",
                    "offerImagePath",
                    "status",
                    "description",
                    "startDate",
                    "endDate"
                  ]
                },
                "planDuration": {
                  "type": "integer"
                },
                "planType": {
                  "type": "string"
                },
                "monthlyPackage": {
                  "type": "integer"
                },
                "swapCount": {
                  "type": "integer"
                },
                "dailyPayValue": {
                  "type": "integer"
                },
                "percentageBenefit": {
                  "type": "integer"
                },
                "costOnDemand": {
                  "type": "integer"
                },
                "costSaving": {
                  "type": "integer"
                },
                "status": {
                  "type": "integer"
                },
                "isAvailed": {
                  "type": "integer"
                }
              },
              "required": [
                "lastUpdatedDate",
                "lastUpdatedBy",
                "createdDate",
                "createdBy",
                "id",
                "offer",
                "planDuration",
                "planType",
                "monthlyPackage",
                "swapCount",
                "dailyPayValue",
                "percentageBenefit",
                "costOnDemand",
                "costSaving",
                "status",
                "isAvailed"
              ]
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            },
            "status": {
              "type": "integer"
            },
            "availedSwaps": {
              "type": "integer"
            },
            "totalAmountPaid": {
              "type": "integer"
            },
            "daysPaid": {
              "type": "integer"
            },
            "missedDays": {
              "type": "integer"
            },
            "overdueAmount": {
              "type": "integer"
            }
          },
          "required": [
            "lastUpdatedDate",
            "lastUpdatedBy",
            "createdDate",
            "createdBy",
            "id",
            "customerId",
            "energyPlanInfo",
            "startDate",
            "endDate",
            "status",
            "availedSwaps",
            "totalAmountPaid",
            "daysPaid",
            "missedDays",
            "overdueAmount"
          ]
        }
      ]
    }
  },
  "required": [
    "message",
    "success",
    "status",
    "response"
  ]
}

=== Ajay-Chandrasekaran/rest-automation/src/test/resources/energyPlan/allEnergyPlans.json
{"message":"Energy Plan is fetched successfully","success":true,"status":200,"response":[{"lastUpdatedDate":"2023-09-07T12:53:54.015778","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-07T12:53:54.01576","createdBy":"ATHENA_PORTAL","id":7,"offer":{"lastUpdatedDate":"2023-09-07T12:53:54.013127","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-07T12:53:54.01311","createdBy":"ATHENA_PORTAL","offerCode":"E20","offerName":"E_PLAN_10","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-07","endDate":"2023-09-10"},"planDuration":0,"planType":null,"monthlyPackage":0,"swapCount":0,"dailyPayValue":193.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-08T11:33:06.476446","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-06T11:51:29.019132","createdBy":"ATHENA_PORTAL","id":2,"offer":{"lastUpdatedDate":"2023-09-08T11:33:06.475367","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-06T11:51:29.012976","createdBy":"ATHENA_PORTAL","offerCode":"E01","offerName":"EnergyPlan_1","countryCode":"TG","countryName":"Togo","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-06","endDate":"2023-11-06"},"planDuration":0,"planType":null,"monthlyPackage":5000,"swapCount":5,"dailyPayValue":193.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T10:34:25.152741","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:32:49.508604","createdBy":"ATHENA_PORTAL","id":38,"offer":{"lastUpdatedDate":"2023-09-12T10:34:25.151809","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:32:49.506353","createdBy":"ATHENA_PORTAL","offerCode":"TESTPLAN02","offerName":"Test_Plan_one","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-12","endDate":"2023-09-13"},"planDuration":0,"planType":null,"monthlyPackage":200,"swapCount":2,"dailyPayValue":100.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T10:36:39.03201","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:36:39.032002","createdBy":"ATHENA_PORTAL","id":39,"offer":{"lastUpdatedDate":"2023-09-12T10:36:39.030391","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:36:39.03038","createdBy":"ATHENA_PORTAL","offerCode":"TESTPLAN02","offerName":"Test_Plan_one","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-12","endDate":"2023-09-13"},"planDuration":0,"planType":null,"monthlyPackage":200,"swapCount":2,"dailyPayValue":100.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T10:37:05.933237","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:37:05.933228","createdBy":"ATHENA_PORTAL","id":40,"offer":{"lastUpdatedDate":"2023-09-12T10:37:05.9319","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:37:05.931889","createdBy":"ATHENA_PORTAL","offerCode":"TESTPLAN02","offerName":"Test_Plan_one","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-12","endDate":"2023-10-13"},"planDuration":0,"planType":null,"monthlyPackage":200,"swapCount":2,"dailyPayValue":100.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T10:39:09.74299","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:38:17.52289","createdBy":"ATHENA_PORTAL","id":41,"offer":{"lastUpdatedDate":"2023-09-12T10:39:09.742305","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:38:17.521407","createdBy":"ATHENA_PORTAL","offerCode":"TESTPLAN03","offerName":"Test_Plan_one","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-12","endDate":"2023-10-13"},"planDuration":0,"planType":null,"monthlyPackage":200,"swapCount":2,"dailyPayValue":100.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T10:55:45.07285","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:39:31.619507","createdBy":"ATHENA_PORTAL","id":42,"offer":{"lastUpdatedDate":"2023-09-12T10:55:45.071065","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:39:31.618319","createdBy":"ATHENA_PORTAL","offerCode":"E1","offerName":"E1","countryCode":null,"countryName":null,"offerImagePath":null,"status":2,"description":null,"startDate":"2023-09-12","endDate":"2023-12-12"},"planDuration":0,"planType":null,"monthlyPackage":15000,"swapCount":15,"dailyPayValue":530.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T11:01:36.733891","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:59:03.320142","createdBy":"ATHENA_PORTAL","id":43,"offer":{"lastUpdatedDate":"2023-09-12T11:01:36.733024","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T10:59:03.318895","createdBy":"ATHENA_PORTAL","offerCode":"E15","offerName":"EnergyPlan_15","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-07","endDate":"2023-09-10"},"planDuration":0,"planType":null,"monthlyPackage":20000,"swapCount":9,"dailyPayValue":193.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0},{"lastUpdatedDate":"2023-09-12T11:02:30.691423","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T11:02:30.691415","createdBy":"ATHENA_PORTAL","id":44,"offer":{"lastUpdatedDate":"2023-09-12T11:02:30.68942","lastUpdatedBy":"ATHENA_PORTAL","createdDate":"2023-09-12T11:02:30.68941","createdBy":"ATHENA_PORTAL","offerCode":"E15","offerName":"EnergyPlan_15","countryCode":"BJ","countryName":"Benin","offerImagePath":null,"status":1,"description":null,"startDate":"2023-09-07","endDate":"2023-09-10"},"planDuration":0,"planType":null,"monthlyPackage":20000,"swapCount":9,"dailyPayValue":193.0,"percentageBenefit":0.0,"costOnDemand":0.0,"costSaving":0.0,"status":0,"isAvailed":0}]}
